Repository thoth-station/build-analyzers, pull requests merged in 2019-12, with the labels that each got.

#93 Change Sphinx theme
  docs/source/conf.py
Labels: size/XS

#94 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: bot, size/L

#95 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#96 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/XS

#97 Automatic update of dependency numpy from 1.17.4 to 1.18.0rc1
  Pipfile.lock
Labels: bot, size/M

#98 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/S

#99 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#100 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: bot, size/S

#102 Automatic update of dependency plotly from 4.3.0 to 4.4.1
  Pipfile.lock
Labels: bot, size/L

#104 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/M

#105 Automatic update of dependency parse from 1.12.1 to 1.13.0
  Pipfile.lock
Labels: bot, size/L

#106 Automatic update of dependency numpy from 1.18.0rc1 to 1.18.0
  Pipfile.lock
Labels: bot, size/L

#107 Automatic update of dependency parse from 1.13.0 to 1.13.1
  Pipfile.lock
Labels: bot, size/XS

#108 Automatic update of dependency parse from 1.13.1 to 1.14.0
  Pipfile.lock
Labels: bot, size/XS
