Repository thoth-station/build-analyzers, pull requests merged in 2019-07, with the labels that each got.

#31 Required scripts and symlink for cli
  app.sh
  thoth-build-analyser
Labels: approved, size/S

#32 Added required env vars and templates for the build analyser cli
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-build-analyse-template.yaml
  openshift/job-build-dependencies-template.yaml
  openshift/job-build-report-template.yaml
  thoth/build_analysers/cli.py
Labels: approved, size/XL

#34 Add codeowners
  .github/CODEOWNERS
Labels: approved, size/XS

#33 modified cli to submit results to result-api
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/build_analysers/cli.py
Labels: approved, size/L, size/XXL

#35 Modified the names to standard convention
  MANIFEST.in
  README.md
  app.sh
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-build-analyze-template.yaml
  openshift/job-build-dependencies-template.yaml
  openshift/job-build-report-template.yaml
  pyproject.toml
  setup.py
  thoth-build-analyser
  thoth-build-analyzer
  thoth/build_analyzers/__about__.py
  thoth/build_analyzers/__init__.py
  thoth/build_analyzers/analysis.py
  thoth/build_analyzers/cli.py
  thoth/build_analyzers/parsing/__init__.py
  thoth/build_analyzers/parsing/handlers/__init__.py
  thoth/build_analyzers/parsing/handlers/base.py
  thoth/build_analyzers/parsing/handlers/dnf.py
  thoth/build_analyzers/parsing/handlers/pip.py
  thoth/build_analyzers/parsing/handlers/pip3.py
  thoth/build_analyzers/parsing/handlers/pipenv.py
  thoth/build_analyzers/parsing/handlers/yum.py
  thoth/build_analyzers/preprocessing.py
  thoth/build_analyzers/resources/patterns.pip.csv
  thoth/build_analyzers/resources/patterns.pipenv.csv
Labels: size/L

#36 changes after the structure change of build_log json
  thoth/build_analyzers/cli.py
Labels: approved, size/XS

#37 Add files needed for generating documentation
  .coafile
  docs/source/_static/EMPTY
  docs/source/_templates/EMPYT
  docs/source/conf.py
  docs/source/index.rst
Labels: approved, size/L

#38 updated zuul config to trigger build in openshift
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/S
