Repository thoth-station/build-analyzers, pull requests merged in 2019-08, with the labels that each got.

#39 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#40 Added config
  .thoth.yaml
Labels: approved, size/S

#41 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M
