Repository thoth-station/build-analyzers, pull requests merged in 2019-11, with the labels that each got.

#79 Automatic update of dependency pandas from 0.25.2 to 0.25.3
  Pipfile.lock
Labels: bot

#80 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#81 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#82 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#83 Automatic update of dependency numpy from 1.17.3 to 1.17.4
  Pipfile.lock
Labels: bot

#84 Automatic update of dependency plotly from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot

#85 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#86 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.21
  Pipfile.lock
Labels: bot, size/L

#87 Automatic update of dependency thoth-storages from 0.19.21 to 0.19.22
  Pipfile.lock
Labels: bot, size/XS

#88 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#89 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#90 Propagate document id to jobs
  openshift/job-build-analyze-template.yaml
  openshift/job-build-dependencies-template.yaml
  openshift/job-build-report-template.yaml
Labels: approved

#91 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, size/L

#92 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/M
