Repository thoth-station/build-analyzers, pull requests merged in 2019-09, with the labels that each got.

#43 Automatic update of dependency numpy from 1.17.0rc1 to 1.17.2
  Pipfile.lock
Labels: approved, bot

#44 Automatic update of dependency pandas from 0.25.0rc0 to 0.25.1
  Pipfile.lock
Labels: approved, bot

#45 Automatic update of dependency plotly from 4.0.0rc1 to 4.1.1
  Pipfile.lock
Labels: approved, bot

#46 Automatic update of dependency parse from 1.12.0 to 1.12.1
  Pipfile.lock
Labels: approved, bot

#48 Automatic update of dependency thoth-storages from 0.14.7 to 0.19.1
  Pipfile.lock
Labels: approved, bot

#49 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: approved, bot

#50 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: approved, bot

#51 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#52 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#55 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.7
  Pipfile.lock
Labels: bot

#53 Automatic update of dependency thoth-analyzer from 0.1.2 to 0.1.3
  Pipfile.lock
Labels: bot

#56 Add duration to Build-Analyzers
  thoth/build_analyzers/cli.py
Labels: approved, size/S, size/XS

#58 Automatic update of dependency thoth-analyzer from 0.1.3 to 0.1.4
  Pipfile.lock
Labels: bot

#57 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#59 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot
