Repository thoth-station/build-analyzers, pull requests merged in 2019-10, with the labels that each got.

#61 Automatic update of dependency networkx from 2.3 to 2.4rc1
  Pipfile.lock
Labels: approved, bot

#65 Automatic update of dependency networkx from 2.4rc1 to 2.4
  Pipfile.lock
Labels: bot

#64 Automatic update of dependency plotly from 4.1.1 to 4.2.0
  Pipfile.lock
Labels: bot

#66 Automatic update of dependency numpy from 1.17.2 to 1.17.3
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency pandas from 0.25.1 to 0.25.2
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#70 Automatic update of dependency plotly from 4.2.0 to 4.2.1
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#71 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#73 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#74 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#75 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-build-analyze-template.yaml
  openshift/job-build-dependencies-template.yaml
  openshift/job-build-report-template.yaml
Labels: approved, size/M

#76 Automatic update of dependency black from 19.3b0 to 19.10b0
  Pipfile.lock
Labels: bot

#77 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#78 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
