Repository thoth-station/build-analyzers, pull requests merged in 2019-04, with the labels that each got.

#2 Removed the old files which are not being used.
  Jenkinsfile
  app.py
  thoth_build_analysers/__init__.py
  thoth_build_analysers/apis/__init__.py
  thoth_build_analysers/apis/openshift.py
  thoth_build_analysers/configuration.py
  thoth_build_analysers/exceptions.py
  thoth_build_analysers/openshift.py
  tox.ini
Labels: approved, size/L

#3 Additional cleanup
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  features/analyse.feature
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  setup.cfg
  setup.py
  tests/__init__.py
  tests/test_analyse.py
Labels: size/XXL

#4 Migrate parsing library from thoth/user-api repository
  thoth/build_analysers/__about__.py
  thoth/build_analysers/__init__.py
  thoth/build_analysers/parsing/__init__.py
  thoth/build_analysers/parsing/handlers/__init__.py
  thoth/build_analysers/parsing/handlers/base.py
  thoth/build_analysers/parsing/handlers/dnf.py
  thoth/build_analysers/parsing/handlers/pip.py
  thoth/build_analysers/parsing/handlers/pip3.py
  thoth/build_analysers/parsing/handlers/yum.py
Labels: size/XL

#7 Preprocessing
  thoth/build_analysers/__init__.py
  thoth/build_analysers/preprocessing.py
Labels: size/L

#9 Thoth configuration files
  .coafile
  .thoth.yaml
  .zuul.yaml
  pyproject.toml
Labels: approved, size/M

#10 Format codebase with black
  thoth/build_analysers/__about__.py
  thoth/build_analysers/__init__.py
  thoth/build_analysers/parsing/__init__.py
  thoth/build_analysers/parsing/handlers/base.py
  thoth/build_analysers/parsing/handlers/pip3.py
  thoth/build_analysers/parsing/handlers/yum.py
  thoth/build_analysers/preprocessing.py
Labels: approved, size/L

#8 Migrate analysis logic from notebook
  thoth/build_analysers/analysis.py
  thoth/build_analysers/resources/patterns.pip.csv
  thoth/build_analysers/resources/patterns.pipenv.csv
Labels: approved, size/L, size/XL

#12 Remove duplicite definition and add check for pip
  thoth/build_analysers/analysis.py
  thoth/build_analysers/parsing/handlers/pip3.py
  thoth/build_analysers/preprocessing.py
Labels: approved, size/M, size/S

#13 Setuptools
  MANIFEST.in
  Pipfile
  pyproject.toml
  requirements.txt
  setup.py
  thoth/build_analysers/__about__.py
  thoth/build_analysers/__init__.py
Labels: approved, size/L

#15 Return iterable of patterns instead of the whole DF
  thoth/build_analysers/analysis.py
Labels: approved, size/S

#17 Specify 'python' engine in the query
  thoth/build_analysers/analysis.py
Labels: approved, size/XS
