Repository thoth-station/build-analyzers, pull requests merged in 2020-02, with the labels that each got.

#141 Automatic update of dependency pandas from 1.0.0 to 1.0.1
  Pipfile.lock
Labels: bot, size/M

#143 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot

#142 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#144 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/M

#145 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#147 Automatic update of dependency plotly from 4.5.0 to 4.5.1
  Pipfile.lock
Labels: bot, size/L

#148 Automatic update of dependency plotly from 4.5.1 to 4.5.2
  Pipfile.lock
Labels: bot, size/L

#149 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot, size/M

#150 Automatic update of dependency parse from 1.14.0 to 1.15.0
  Pipfile.lock
Labels: bot, size/M
