Repository thoth-station/build-analyzers, pull requests merged in 2020-04, with the labels that each got.

#161 Automatic update of dependency plotly from 4.5.4 to 4.6.0
  Pipfile.lock
Labels: bot, size/M

#162 Automatic update of dependency thoth-lab from 0.1.8 to 0.1.9
  Pipfile.lock
Labels: bot, size/S

#163 Automatic update of dependency thoth-lab from 0.1.9 to 0.1.10
  Pipfile.lock
Labels: bot, size/L

#164 Automatic update of dependency autopep8 from 1.5 to 1.5.1
  Pipfile.lock
Labels: bot, size/L

#166 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#169 Automatic update of dependency pandas from 0.25.3 to 1.0.3
  Pipfile.lock
Labels: bot, size/L

#170 Automatic update of dependency numpy from 1.18.2 to 1.18.3
  Pipfile.lock
Labels: bot, size/L

#171 Automatic update of dependency autopep8 from 1.5.1 to 1.5.2
  Pipfile.lock
Labels: bot, size/S

#177 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/L

#179 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/M

#181 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/S
