Repository thoth-station/build-analyzers, pull requests merged in 2020-01, with the labels that each got.

#109 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/M

#110 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#111 Happy new year!
  docs/source/conf.py
  setup.py
  thoth/build_analyzers/__init__.py
  thoth/build_analyzers/analysis.py
  thoth/build_analyzers/cli.py
  thoth/build_analyzers/parsing/__init__.py
  thoth/build_analyzers/parsing/handlers/__init__.py
  thoth/build_analyzers/parsing/handlers/base.py
  thoth/build_analyzers/parsing/handlers/dnf.py
  thoth/build_analyzers/parsing/handlers/pip.py
  thoth/build_analyzers/parsing/handlers/pip3.py
  thoth/build_analyzers/parsing/handlers/pipenv.py
  thoth/build_analyzers/parsing/handlers/yum.py
  thoth/build_analyzers/preprocessing.py
Labels: approved, size/S

#112 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: bot, size/XS

#113 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: bot, size/S

#114 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#115 Automatic update of dependency numpy from 1.18.0 to 1.18.1
  Pipfile.lock
Labels: bot, size/L

#116 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.5
  Pipfile.lock
Labels: bot, size/M

#117 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#118 Automatic update of dependency thoth-storages from 0.20.5 to 0.20.6
  Pipfile.lock
Labels: bot, size/M

#119 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#120 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/S

#121 Automatic update of dependency pandas from 0.25.3 to 1.0.0rc0
  Pipfile.lock
Labels: bot, size/M

#122 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/XS

#123 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/S

#124 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/M

#125 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/XS

#127 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/M

#126 Minor Fix, type check
  thoth/build_analyzers/analysis.py
  thoth/build_analyzers/cli.py
Labels: approved, size/S

#128 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/M

#129 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/S

#130 Automatic update of dependency autopep8 from 1.4.4 to 1.5
  Pipfile.lock
Labels: bot, size/M

#131 Automatic update of dependency thoth-storages from 0.21.7 to 0.21.8
  Pipfile.lock
Labels: bot, size/S

#132 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/S

#133 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#135 Automatic update of dependency plotly from 4.4.1 to 4.5.0rc1
  Pipfile.lock
Labels: bot, size/M

#136 Automatic update of dependency plotly from 4.5.0rc1 to 4.5.0
  Pipfile.lock
Labels: bot, size/XS

#137 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/L

#139 Automatic update of dependency pandas from 1.0.0rc0 to 1.0.0
  Pipfile.lock
Labels: bot, size/L

#140 compatible with graph-sync-scheduler
  openshift/job-build-analyze-template.yaml
  openshift/job-build-dependencies-template.yaml
  openshift/job-build-report-template.yaml
Labels: approved, size/XS
